#!/bin/bash

#SADB=/data/mail/spamassassin
dbpath=$(fgrep bayes_path /etc/spamassassin/local.cf | awk '{print $2}')
ARGS="--dbpath $dbpath --progress"

nice -n 19 sa-learn $ARGS --no-sync --ham /home/{brandon,amy}/Maildir/cur  2>&1
nice -n 19 sa-learn $ARGS --no-sync --spam /home/{brandon,amy}/Maildir/.Junk/cur 2>&1
nice -n 19 sa-learn $ARGS --sync 2>&1
chown -R 990:990 $(dirname $dbpath)
