#!/bin/bash

exit

# if using AWS ECS...

# using virtualenv, we have a known good version of aws cli here
if [ -d ~/vaws ]; then
	source ~/vaws/bin/activate
fi

# get login and activate it
$(aws ecr get-login)
